openapi: 3.0.0
info:
  title: AAA API
  version: 1.0.0
  description: AAA
paths: {}
components:
  schemas:
    Description:
      type: object
      required:
        - id
        - origin
        - number
        - condition
        - dimensions
        - attributes
      properties:
        id:
          type: integer
          format: int64
        origin:
          type: array
          items:
            type: string
        number:
          type: integer
          format: int64
        condition:
          type: string
        dimensions:
          type: array
          items:
            type: number
            format: int64
        attributes:
          type: array
          items:
            $ref: '#/components/schemas/ArtifactAttribute'
    ArtifactAttribute:
      type: object
      required:
        - id
        - type
      properties:
        id:
          type: string
        type:
          type: string
    History:
      type: object
      required:
        - id
        - entries
      properties:
        id:
          type: integer
          format: int64
        entries:
          type: array
          items:
            $ref: '#/components/schemas/HistoryEntry'
    HistoryEntry:
      type: object
      required:
        - date
        - amount
      properties:
        date:
          type: string
          format: date
        amount:
          type: string
          format: decimal
    Images:
      type: object
      required:
        - id
        - images
      properties:
        id:
          type: integer
          format: int64
        images:
          type: array
          items:
            $ref: '#/components/schemas/ImageUrl'
    ImageUrl:
      type: object
      required:
        - url
      properties:
        url:
          type: string
    PaymentMethods:
      type: array
      items:
        $ref: '#/components/schemas/PaymentMethod'
    PaymentMethod:
      type: object
      required:
        - url
        - value
      properties:
        url:
          type: string
        value:
          type: string
    ContactDetails:
      type: object
      required:
        - name
        - mailId
        - phoneNumber
        - coordinates
      properties:
        name:
          type: string
        mailId:
          type: string
        phoneNumber:
          type: object
          required:
            - number
            - prefix
          properties:
            prefix:
              type: string
            number:
              nullable: true
              type: number
              format: int64
        coordinates:
          type: object
          required:
            - lat
            - long
          properties:
            lat:
              $ref: '#/components/schemas/Coordinate'
            long:
              $ref: '#/components/schemas/Coordinate'
    Coordinate:
      type: object
      required:
        - prefix1
        - prefix2
        - prefix3
        - coordinate
      properties:
        prefix1:
          type: string
        prefix2:
          type: string
        prefix3:
          type: string
        coordinate:
          type: number
          format: float
          nullable: true
    PaymentDetails:
      type: object
      required:
        - paymentMethod
        - cardNumber
      properties:
        paymentMethod:
          type: string
        cardNumber:
          type: number
          format: int64
          nullable: true
    SecurityCode:
      type: object
      required:
        - c
        - m
        - y
      properties:
        c:
          type: string
        m:
          type: string
        y:
          type: string
